### ISSUE TITLE
plone.subrequest Unauthorized error

### ISSUE THREAD

**Issue by Gomez** [collective/plonetheme.webpacktemplate#19]
We noticed this error as a non admin user. As admin this error does not happen.

```
2020-02-05 11:28:39 ERROR plone.subrequest Error handling subrequest to /esd/front-page/++theme++barceloneta/rules.xml                      
Traceback (most recent call last):
  File "/home/gomez/.cache/buildout/eggs/plone.subrequest-1.8.6-py2.7.egg/plone/subrequest/__init__.py", line 153, in subrequest            
    traversed = request.traverse(path)
  File "/home/gomez/.cache/buildout/eggs/Zope2-2.13.27-py2.7.egg/ZPublisher/BaseRequest.py", line 623, in traverse                          
    response.unauthorized()
  File "/home/gomez/.cache/buildout/eggs/Zope2-2.13.27-py2.7.egg/ZPublisher/HTTPResponse.py", line 756, in unauthorized                     
    raise Unauthorized, m
Unauthorized: You are not authorized to access this resource.
[2] > /home/gomez/.cache/buildout/eggs/Zope2-2.13.27-py2.7.egg/ZPublisher/HTTPResponse.py(756)unauthorized()                                
-> raise Unauthorized, m
(Pdb++)
```

@datakurre As you worked with this lately, i paste it here. We have not debugged into it, but we will. Maybe you have a idea or seen it before?

**Comment by datakurre** [comment]
@Gomez Is /esd/front-page/ private?

I believe /esd/front-page/++theme++barceloneta/rules.xml should probably be /esd/++theme++barceloneta/rules.xml instead somehow.

I recall that diazo, you could use absolute root /++theme++barceloneta/rules.xml in your rules and plone.app.theming would transform that into /esd/++theme++barceloneta/rules.xml

**Comment by Gomez** [comment]
/esd/front-page/ is inside plone not in the filesystem. I already tried absolute paths in this project. 

Have a similar error on a fresh project right now. Will debug...

**Comment by Gomez** [comment]
Found it :)

rules.xml was imported twice from another theme package.

**Comment by datakurre** [comment]
Good to know. Really confusing error regarding that.
